local Items = {}

Items.items = {
    --bob-alien-resource
    ["bob-alien-blue-alloy"] = { tech = "bob-alien-blue-research", type = "item" },
    ["bob-alien-orange-alloy"] = { tech = "bob-alien-orange-research", type = "item" },
    --bob-alloy
    ["bob-brass-alloy"] = { tech = "bob-zinc-processing", type = "item" },
    ["bob-bronze-alloy"] = { tech = "bob-alloy-processing-1", type = "item" },
    ["bob-cobalt-steel-alloy"] = { tech = "bob-cobalt-processing", type = "item" },
    ["bob-copper-tungsten-alloy"] = { tech = "bob-tungsten-alloy-processing", type = "item" },
    ["bob-gunmetal-alloy"] = { tech = "bob-zinc-processing", type = "item" },
    ["bob-invar-alloy"] = { tech = "bob-invar-processing", type = "item" },
    ["bob-nitinol-alloy"] = { tech = "bob-nitinol-processing", type = "item" },
    ["bob-solder-alloy"] = { tech = "bob-electronics", type = "item" },
    ["bob-tungsten-carbide"] = { tech = "bob-tungsten-alloy-processing", type = "item" },
    --bob-bearings
    ["bob-ceramic-bearing"] = { tech = "bob-ceramics", type = "item" },
    ["bob-ceramic-bearing-ball"] = { tech = "bob-ceramics", type = "item" },
    ["bob-cobalt-steel-bearing"] = { tech = "bob-cobalt-processing", type = "item" },
    ["bob-cobalt-steel-bearing-ball"] = { tech = "bob-cobalt-processing", type = "item" },
    ["bob-nitinol-bearing"] = { tech = "bob-nitinol-processing", type = "item" },
    ["bob-nitinol-bearing-ball"] = { tech = "bob-nitinol-processing", type = "item" },
    ["bob-steel-bearing"] = { tech = "bob-steel-processing", type = "item" },
    ["bob-steel-bearing-ball"] = { tech = "bob-steel-processing", type = "item" },
    ["bob-titanium-bearing"] = { tech = "bob-titanium-processing", type = "item" },
    ["bob-titanium-bearing-ball"] = { tech = "bob-titanium-processing", type = "item" },
    --bob-boards
    ["bob-fibreglass-board"] = { tech = "bob-advanced-electronics-2", type = "item" },
    ["bob-phenolic-board"] = { tech = "bob-advanced-electronics", type = "item" },
    ["bob-wooden-board"] = { tech = "DEFAULT", type = "item" },
    --bob-electronic-boards
    -- ["bob-advanced-circuit"] = { tech = "bob-advanced-electronics", type = "item", reskin = true },
    ["bob-advanced-circuit"] = { tech = "bob-advanced-electronics", type = "item" },
    ["bob-advanced-processing-unit"] = { tech = "bob-advanced-electronics-3", type = "item" },
    ["bob-basic-circuit-board"] = { tech = "DEFAULT", type = "item" },
    ["bob-circuit-board"] = { tech = "bob-advanced-electronics", type = "item" },
    -- ["bob-electronic-circuit"] = { tech = "bob-electronics", type = "item", reskin = true },
    ["bob-electronic-circuit"] = { tech = "bob-electronics", type = "item" },
    ["bob-multi-layer-circuit-board"] = { tech = "bob-advanced-electronics-3", type = "item" },
    -- ["bob-processing-unit"] = { tech = "bob-advanced-electronics-2", type = "item", reskin = true },
    ["bob-processing-unit"] = { tech = "bob-advanced-electronics-2", type = "item" },
    ["bob-superior-circuit-board"] = { tech = "bob-advanced-electronics-2", type = "item" },
    --bob-electronic-components
    ["bob-basic-electronic-components"] = { tech = "bob-electronics", type = "item" },
    ["bob-electronic-components"] = { tech = "bob-advanced-electronics", type = "item" },
    ["bob-gilded-copper-cable"] = { tech = "bob-advanced-electronics-3", type = "item" },
    ["bob-insulated-cable"] = { tech = "bob-electronics", type = "item" },
    ["bob-intergrated-electronics"] = { tech = "bob-advanced-electronics-2", type = "item" },
    ["bob-processing-electronics"] = { tech = "bob-advanced-electronics-3", type = "item" },
    ["bob-solder"] = { tech = "bob-electronics", type = "item" },
    ["bob-tinned-copper-cable"] = { tech = "bob-electronics", type = "item" },
    --bob-gears
    ["bob-brass-gear-wheel"] = { tech = "bob-zinc-processing", type = "item" },
    ["bob-cobalt-steel-gear-wheel"] = { tech = "bob-cobalt-processing", type = "item" },
    ["bob-nitinol-gear-wheel"] = { tech = "bob-nitinol-processing", type = "item" },
    ["bob-steel-gear-wheel"] = { tech = "bob-steel-processing", type = "item" },
    ["bob-titanium-gear-wheel"] = { tech = "bob-titanium-processing", type = "item" },
    ["bob-tungsten-gear-wheel"] = { tech = "bob-tungsten-processing", type = "item" },
    --bob-gems-cut
    ["bob-amethyst-4"] = { tech = "bob-gem-processing-1", type = "item" },
    ["bob-diamond-4"] = { tech = "bob-gem-processing-1", type = "item" },
    ["bob-emerald-4"] = { tech = "bob-gem-processing-1", type = "item" },
    ["bob-ruby-4"] = { tech = "bob-gem-processing-1", type = "item" },
    ["bob-sapphire-4"] = { tech = "bob-gem-processing-1", type = "item" },
    ["bob-topaz-4"] = { tech = "bob-gem-processing-1", type = "item" },
    --bob-gems-polished
    ["bob-amethyst-5"] = { tech = "bob-gem-processing-2", type = "item" },
    ["bob-diamond-5"] = { tech = "bob-gem-processing-2", type = "item" },
    ["bob-emerald-5"] = { tech = "bob-gem-processing-2", type = "item" },
    ["bob-ruby-5"] = { tech = "bob-gem-processing-2", type = "item" },
    ["bob-sapphire-5"] = { tech = "bob-gem-processing-2", type = "item" },
    ["bob-topaz-5"] = { tech = "bob-gem-processing-2", type = "item" },
    --bob-gems-raw
    ["bob-amethyst-3"] = { tech = "bob-deadlock-stacking-1", type = "item" },
    ["bob-diamond-3"] = { tech = "bob-deadlock-stacking-1", type = "item" },
    ["bob-emerald-3"] = { tech = "bob-deadlock-stacking-1", type = "item" },
    ["bob-ruby-3"] = { tech = "bob-deadlock-stacking-1", type = "item" },
    ["bob-sapphire-3"] = { tech = "bob-deadlock-stacking-1", type = "item" },
    ["bob-topaz-3"] = { tech = "bob-deadlock-stacking-1", type = "item" },
    --bob-greenhouse-items
    ["bob-seedling"] = { tech = "bob-bob-greenhouse", type = "item" },
    --bob-intermediates
    ["bob-grinding-wheel"] = { tech = "bob-grinding", type = "item" },
    ["bob-lithium-ion-battery"] = { tech = "bob-battery-2", type = "item" },
    ["bob-polishing-wheel"] = { tech = "bob-polishing", type = "item" },
    ["bob-rocket-engine"] = { tech = "bob-rocketry", type = "item" },
    ["bob-silver-zinc-battery"] = { tech = "bob-battery-3", type = "item" },
    --bob-logistic-tier-0
    ["bob-basic-transport-belt"] = { tech = "bob-deadlock-stacking-1", type = "item" },
    ["bob-basic-underground-belt"] = { tech = "bob-logistics-0", type = "item" },
    ["bob-basic-splitter"] = { tech = "bob-logistics-0", type = "item" },
    ["bob-burner-inserter"] = { tech = "bob-deadlock-stacking-1", type = "item" },
    --bob-logistic-tier-1
    ["bob-transport-belt"] = { tech = "bob-logistics", type = "item" },
    ["bob-underground-belt"] = { tech = "bob-logistics", type = "item" },
    ["bob-splitter"] = { tech = "bob-logistics", type = "item" },
    ["bob-inserter"] = { tech = "bob-deadlock-stacking-1", type = "item" },
    ["bob-yellow-filter-inserter"] = { tech = "bob-electronics", type = "item" },
    --bob-logistic-tier-2
    ["bob-fast-transport-belt"] = { tech = "bob-logistics-2", type = "item" },
    ["bob-fast-underground-belt"] = { tech = "bob-logistics-2", type = "item" },
    ["bob-fast-splitter"] = { tech = "bob-logistics-2", type = "item" },
    ["bob-long-handed-inserter"] = { tech = "bob-fast-inserter", type = "item" },
    ["bob-red-filter-inserter"] = { tech = "bob-fast-inserter", type = "item" },
    ["bob-red-stack-filter-inserter"] = { tech = "bob-stack-inserter", type = "item" },
    ["bob-red-stack-inserter"] = { tech = "bob-stack-inserter", type = "item" },
    --bob-logistic-tier-3
    ["bob-express-transport-belt"] = { tech = "bob-logistics-3", type = "item" },
    ["bob-express-underground-belt"] = { tech = "bob-logistics-3", type = "item" },
    ["bob-express-splitter"] = { tech = "bob-logistics-3", type = "item" },
    ["bob-fast-inserter"] = { tech = "bob-express-inserters", type = "item" },
    ["bob-filter-inserter"] = { tech = "bob-express-inserters", type = "item" },
    ["bob-stack-filter-inserter"] = { tech = "bob-stack-inserter-2", type = "item" },
    ["bob-stack-inserter"] = { tech = "bob-stack-inserter-2", type = "item" },
    --bob-logistic-tier-4
    ["bob-turbo-transport-belt"] = { tech = "bob-logistics-4", type = "item" },
    ["bob-turbo-underground-belt"] = { tech = "bob-logistics-4", type = "item" },
    ["bob-turbo-splitter"] = { tech = "bob-logistics-4", type = "item" },
    ["bob-turbo-filter-inserter"] = { tech = "bob-turbo-inserter", type = "item" },
    ["bob-turbo-inserter"] = { tech = "bob-turbo-inserter", type = "item" },
    ["bob-turbo-stack-filter-inserter"] = { tech = "bob-stack-inserter-3", type = "item" },
    ["bob-turbo-stack-inserter"] = { tech = "bob-stack-inserter-3", type = "item" },
    --bob-logistic-tier-5
    ["bob-ultimate-transport-belt"] = { tech = "bob-logistics-5", type = "item" },
    ["bob-ultimate-underground-belt"] = { tech = "bob-logistics-5", type = "item" },
    ["bob-ultimate-splitter"] = { tech = "bob-logistics-5", type = "item" },
    ["bob-express-filter-inserter"] = { tech = "bob-ultimate-inserter", type = "item" },
    ["bob-express-inserter"] = { tech = "bob-ultimate-inserter", type = "item" },
    ["bob-express-stack-filter-inserter"] = { tech = "bob-stack-inserter-4", type = "item" },
    ["bob-express-stack-inserter"] = { tech = "bob-stack-inserter-4", type = "item" },
    --bob-material
    ["bob-aluminium-plate"] = { tech = "bob-aluminium-processing", type = "item" },
    ["bob-cobalt-plate"] = { tech = "bob-cobalt-processing", type = "item" },
    ["bob-gold-plate"] = { tech = "bob-gold-processing", type = "item" },
    ["bob-lead-plate"] = { tech = "DEFAULT", type = "item", force_tech = true },
    ["bob-lithium"] = { tech = "bob-lithium-processing", type = "item" },
    ["bob-nickel-plate"] = { tech = "bob-nickel-processing", type = "item" },
    ["bob-plutonium-239"] = { tech = "bob-bobingabout-enrichment-process", type = "item" },
    ["bob-silicon"] = { tech = "bob-silicon-processing", type = "item" },
    ["bob-silver-plate"] = { tech = "bob-deadlock-stacking-1", type = "item" },
    ["bob-thorium-232"] = { tech = "bob-thorium-processing", type = "item" },
    ["bob-tin-plate"] = { tech = "DEFAULT", type = "item" },
    ["bob-titanium-plate"] = { tech = "bob-titanium-processing", type = "item" },
    ["bob-tungsten-plate"] = { tech = "bob-tungsten-processing", type = "item" },
    ["bob-zinc-plate"] = { tech = "bob-zinc-processing", type = "item" },
    --bob-ores
    ["bob-amethyst-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-bauxite-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-cobalt-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-diamond-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-emerald-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-gem-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-gold-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-lead-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-nickel-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-quartz"] = { tech = "DEFAULT", type = "item" },
    ["bob-ruby-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-rutile-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-sapphire-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-silver-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-thorium-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-tin-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-topaz-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-tungsten-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-zinc-ore"] = { tech = "DEFAULT", type = "item" },
    --bob-resource
    ["bob-carbon"] = { tech = "bob-chemical-processing-1", type = "item" },
    ["bob-enriched-fuel"] = { tech = "bob-hydrazine", type = "item" },
    ["bob-glass"] = { tech = "DEFAULT", type = "item" },
    ["bob-gun-cotton"] = { tech = "bob-cordite-processing", type = "item" },
    ["bob-lithium-cobalt-oxide"] = { tech = "bob-battery-2", type = "item" },
    ["bob-petroleum-jelly"] = { tech = "bob-cordite-processing", type = "item" },
    ["bob-polishing-compound"] = { tech = "bob-polishing", type = "item" },
    ["bob-resin"] = { tech = "bob-oil-processing", type = "item" },
    ["bob-rubber"] = { tech = "DEFAULT", type = "item" },
    ["bob-silicon-wafer"] = { tech = "bob-silicon-processing", type = "item" },
    --bob-resource-chemical
    ["bob-alumina"] = { tech = "bob-aluminium-processing", type = "item" },
    ["bob-ammonium-chloride"] = { tech = "bob-rtg", type = "item" },
    ["bob-calcium-chloride"] = { tech = "bob-rtg", type = "item" },
    ["bob-cobalt-oxide"] = { tech = "bob-cobalt-processing", type = "item" },
    ["bob-fertiliser"] = { tech = "bob-bob-fertiliser", type = "item" },
    ["bob-fusion-catalyst"] = { tech = "bob-nuclear-fuel-reprocessing", type = "item" },
    ["bob-lead-oxide"] = { tech = "bob-lead-processing", type = "item" },
    ["bob-limestone"] = { tech = "bob-chemical-processing-2", type = "item" },
    ["bob-lithium-chloride"] = { tech = "bob-lithium-processing", type = "item" },
    ["bob-lithium-perchlorate"] = { tech = "bob-lithium-processing", type = "item" },
    ["bob-powdered-tungsten"] = { tech = "bob-tungsten-processing", type = "item" },
    ["bob-salt"] = { tech = "bob-chemical-processing-1", type = "item" },
    ["bob-silicon-carbide"] = { tech = "bob-grinding", type = "item" },
    ["bob-silicon-nitride"] = { tech = "bob-ceramics", type = "item" },
    ["bob-silicon-powder"] = { tech = "bob-silicon-processing", type = "item" },
    ["bob-silver-nitrate"] = { tech = "bob-battery-3", type = "item" },
    ["bob-silver-oxide"] = { tech = "bob-battery-3", type = "item" },
    ["bob-sodium-bicarbonate"] = { tech = "bob-rtg", type = "item" },
    ["bob-sodium-carbonate"] = { tech = "bob-rtg", type = "item" },
    ["bob-sodium-chlorate"] = { tech = "bob-lithium-processing", type = "item" },
    ["bob-sodium-cobaltate"] = { tech = "bob-rtg", type = "item" },
    ["bob-sodium-hydroxide"] = { tech = "bob-electrolysis-2", type = "item" },
    ["bob-sodium-perchlorate"] = { tech = "bob-lithium-processing", type = "item" },
    ["bob-tungsten-oxide"] = { tech = "bob-tungsten-processing", type = "item" },
    --effectivity-module
    ["bob-effectivity-module"] = { tech = "bob-effectivity-module", type = "module" },
    ["bob-effectivity-module-2"] = { tech = "bob-effectivity-module-2", type = "module" },
    ["bob-effectivity-module-3"] = { tech = "bob-effectivity-module-3", type = "module" },
    ["bob-effectivity-module-4"] = { tech = "bob-effectivity-module-4", type = "module" },
    ["bob-effectivity-module-5"] = { tech = "bob-effectivity-module-5", type = "module" },
    ["bob-effectivity-module-6"] = { tech = "bob-effectivity-module-6", type = "module" },
    ["bob-effectivity-module-7"] = { tech = "bob-effectivity-module-7", type = "module" },
    ["bob-effectivity-module-8"] = { tech = "bob-effectivity-module-8", type = "module" },
    --green-module
    ["bob-green-module-1"] = { tech = "bob-green-module-1", type = "module" },
    ["bob-green-module-2"] = { tech = "bob-green-module-2", type = "module" },
    ["bob-green-module-3"] = { tech = "bob-green-module-3", type = "module" },
    ["bob-green-module-4"] = { tech = "bob-green-module-4", type = "module" },
    ["bob-green-module-5"] = { tech = "bob-green-module-5", type = "module" },
    ["bob-green-module-6"] = { tech = "bob-green-module-6", type = "module" },
    ["bob-green-module-7"] = { tech = "bob-green-module-7", type = "module" },
    ["bob-green-module-8"] = { tech = "bob-green-module-8", type = "module" },
    --intermediate-product
    ["bob-copper-cable"] = { tech = "DEFAULT", type = "item" },
    ["bob-deuterium-fuel-cell"] = { tech = "bob-bob-nuclear-power-3", type = "item" },
    ["bob-electric-engine-unit"] = { tech = "bob-electric-engine", type = "item" },
    ["bob-empty-barrel"] = { tech = "bob-fluid-handling", type = "item" },
    ["bob-engine-unit"] = { tech = "bob-engine", type = "item" },
    ["bob-iron-gear-wheel"] = { tech = "DEFAULT", type = "item" },
    ["bob-iron-stick"] = { tech = "DEFAULT", type = "item" },
    ["bob-low-density-structure"] = { tech = "bob-low-density-structure", type = "item" },
    ["bob-nuclear-fuel"] = { tech = "bob-kovarex-enrichment-process", type = "item" },
    ["bob-plutonium-fuel-cell"] = { tech = "bob-plutonium-fuel-cell", type = "item" },
    ["bob-robot-drone-frame"] = { tech = "bob-robotics", type = "item" },
    ["bob-rocket-control-unit"] = { tech = "bob-rocket-control-unit", type = "item" },
    ["bob-rocket-fuel"] = { tech = "bob-rocket-fuel", type = "item" },
    ["bob-rocket-part"] = { tech = "bob-rocket-silo", type = "item" },
    ["bob-thorium-fuel-cell"] = { tech = "bob-bob-nuclear-power-2", type = "item" },
    ["bob-thorium-plutonium-fuel-cell"] = { tech = "bob-thorium-plutonium-fuel-cell", type = "item" },
    ["bob-uranium-235"] = { tech = "bob-uranium-processing", type = "item" },
    ["bob-uranium-238"] = { tech = "bob-nuclear-fuel-reprocessing", type = "item" },
    ["bob-uranium-fuel-cell"] = { tech = "bob-nuclear-power", type = "item" },
    ["bob-used-up-deuterium-fuel-cell"] = { tech = "bob-deuterium-fuel-reprocessing", type = "item" },
    ["bob-used-up-thorium-fuel-cell"] = { tech = "bob-thorium-fuel-reprocessing", type = "item" },
    ["bob-used-up-uranium-fuel-cell"] = { tech = "bob-nuclear-fuel-reprocessing", type = "item" },
    --module-intermediates
    ["bob-effectivity-processor"] = { tech = "bob-modules", type = "item" },
    ["bob-effectivity-processor-2"] = { tech = "bob-effectivity-module-3", type = "item" },
    ["bob-effectivity-processor-3"] = { tech = "bob-effectivity-module-6", type = "item" },
    ["bob-module-case"] = { tech = "bob-modules", type = "item" },
    ["bob-module-circuit-board"] = { tech = "bob-modules", type = "item" },
    ["bob-module-contact"] = { tech = "bob-modules", type = "item" },
    ["bob-module-processor-board"] = { tech = "bob-modules", type = "item" },
    ["bob-module-processor-board-2"] = { tech = "bob-advanced-electronics-2", type = "item" },
    ["bob-module-processor-board-3"] = { tech = "bob-advanced-electronics-3", type = "item" },
    ["bob-pollution-clean-processor"] = { tech = "bob-modules", type = "item" },
    ["bob-pollution-clean-processor-2"] = { tech = "bob-pollution-clean-module-3", type = "item" },
    ["bob-pollution-clean-processor-3"] = { tech = "bob-pollution-clean-module-6", type = "item" },
    ["bob-pollution-create-processor"] = { tech = "bob-modules", type = "item" },
    ["bob-pollution-create-processor-2"] = { tech = "bob-pollution-create-module-3", type = "item" },
    ["bob-pollution-create-processor-3"] = { tech = "bob-pollution-create-module-6", type = "item" },
    ["bob-productivity-processor"] = { tech = "bob-modules", type = "item" },
    ["bob-productivity-processor-2"] = { tech = "bob-productivity-module-3", type = "item" },
    ["bob-productivity-processor-3"] = { tech = "bob-productivity-module-6", type = "item" },
    ["bob-speed-processor"] = { tech = "bob-modules", type = "item" },
    ["bob-speed-processor-2"] = { tech = "bob-speed-module-3", type = "item" },
    ["bob-speed-processor-3"] = { tech = "bob-speed-module-6", type = "item" },
    --pollution-clean-module
    ["bob-pollution-clean-module-1"] = { tech = "bob-pollution-clean-module-1", type = "module" },
    ["bob-pollution-clean-module-2"] = { tech = "bob-pollution-clean-module-2", type = "module" },
    ["bob-pollution-clean-module-3"] = { tech = "bob-pollution-clean-module-3", type = "module" },
    ["bob-pollution-clean-module-4"] = { tech = "bob-pollution-clean-module-4", type = "module" },
    ["bob-pollution-clean-module-5"] = { tech = "bob-pollution-clean-module-5", type = "module" },
    ["bob-pollution-clean-module-6"] = { tech = "bob-pollution-clean-module-6", type = "module" },
    ["bob-pollution-clean-module-7"] = { tech = "bob-pollution-clean-module-7", type = "module" },
    ["bob-pollution-clean-module-8"] = { tech = "bob-pollution-clean-module-8", type = "module" },
    --pollution-create-module
    ["bob-pollution-create-module-1"] = { tech = "bob-pollution-create-module-1", type = "module" },
    ["bob-pollution-create-module-2"] = { tech = "bob-pollution-create-module-2", type = "module" },
    ["bob-pollution-create-module-3"] = { tech = "bob-pollution-create-module-3", type = "module" },
    ["bob-pollution-create-module-4"] = { tech = "bob-pollution-create-module-4", type = "module" },
    ["bob-pollution-create-module-5"] = { tech = "bob-pollution-create-module-5", type = "module" },
    ["bob-pollution-create-module-6"] = { tech = "bob-pollution-create-module-6", type = "module" },
    ["bob-pollution-create-module-7"] = { tech = "bob-pollution-create-module-7", type = "module" },
    ["bob-pollution-create-module-8"] = { tech = "bob-pollution-create-module-8", type = "module" },
    --productivity-module
    ["bob-productivity-module"] = { tech = "bob-productivity-module", type = "module" },
    ["bob-productivity-module-2"] = { tech = "bob-productivity-module-2", type = "module" },
    ["bob-productivity-module-3"] = { tech = "bob-productivity-module-3", type = "module" },
    ["bob-productivity-module-4"] = { tech = "bob-productivity-module-4", type = "module" },
    ["bob-productivity-module-5"] = { tech = "bob-productivity-module-5", type = "module" },
    ["bob-productivity-module-6"] = { tech = "bob-productivity-module-6", type = "module" },
    ["bob-productivity-module-7"] = { tech = "bob-productivity-module-7", type = "module" },
    ["bob-productivity-module-8"] = { tech = "bob-productivity-module-8", type = "module" },
    --raw-material
    ["bob-alien-artifact"] = { tech = "DEFAULT", type = "item" },
    ["bob-alien-artifact-blue"] = { tech = "DEFAULT", type = "item" },
    ["bob-alien-artifact-green"] = { tech = "DEFAULT", type = "item" },
    ["bob-alien-artifact-orange"] = { tech = "DEFAULT", type = "item" },
    ["bob-alien-artifact-purple"] = { tech = "DEFAULT", type = "item" },
    ["bob-alien-artifact-red"] = { tech = "DEFAULT", type = "item" },
    ["bob-alien-artifact-yellow"] = { tech = "DEFAULT", type = "item" },
    -- ["bob-battery"] = { tech = "bob-battery", type = "item", reskin = true, reskin_mode = 2 },
    ["bob-battery"] = { tech = "bob-battery", type = "item" },
    ["bob-copper-plate"] = { tech = "DEFAULT", type = "item", force_tech = true },
    ["bob-explosives"] = { tech = "bob-explosives", type = "item" },
    ["bob-iron-plate"] = { tech = "DEFAULT", type = "item" },
    ["bob-plastic-bar"] = { tech = "bob-plastics", type = "item" },
    ["bob-small-alien-artifact"] = { tech = "DEFAULT", type = "item" },
    ["bob-small-alien-artifact-blue"] = { tech = "DEFAULT", type = "item" },
    ["bob-small-alien-artifact-green"] = { tech = "DEFAULT", type = "item" },
    ["bob-small-alien-artifact-orange"] = { tech = "DEFAULT", type = "item" },
    ["bob-small-alien-artifact-purple"] = { tech = "DEFAULT", type = "item" },
    ["bob-small-alien-artifact-red"] = { tech = "DEFAULT", type = "item" },
    ["bob-small-alien-artifact-yellow"] = { tech = "DEFAULT", type = "item" },
    ["bob-solid-fuel"] = { tech = "bob-solid-fuel", type = "item" },
    ["bob-steel-plate"] = { tech = "bob-steel-processing", type = "item" },
    ["bob-sulfur"] = { tech = "bob-sulfur-processing", type = "item" },
    --raw-productivity-module
    ["bob-raw-productivity-module-1"] = { tech = "bob-raw-productivity-module-1", type = "module" },
    ["bob-raw-productivity-module-2"] = { tech = "bob-raw-productivity-module-2", type = "module" },
    ["bob-raw-productivity-module-3"] = { tech = "bob-raw-productivity-module-3", type = "module" },
    ["bob-raw-productivity-module-4"] = { tech = "bob-raw-productivity-module-4", type = "module" },
    ["bob-raw-productivity-module-5"] = { tech = "bob-raw-productivity-module-5", type = "module" },
    ["bob-raw-productivity-module-6"] = { tech = "bob-raw-productivity-module-6", type = "module" },
    ["bob-raw-productivity-module-7"] = { tech = "bob-raw-productivity-module-7", type = "module" },
    ["bob-raw-productivity-module-8"] = { tech = "bob-raw-productivity-module-8", type = "module" },
    --raw-resource
    ["bob-coal"] = { tech = "DEFAULT", type = "item" },
    ["bob-copper-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-iron-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-stone"] = { tech = "DEFAULT", type = "item" },
    ["bob-stone-brick"] = { tech = "DEFAULT", type = "item" },
    ["bob-uranium-ore"] = { tech = "DEFAULT", type = "item" },
    ["bob-wood"] = { tech = "DEFAULT", type = "item" },
    ["bob-wood-pellets"] = { tech = "DEFAULT", type = "item" },
    --god-module
    ["bob-god-module-1"] = { tech = "bob-god-module-1", type = "module" },
    ["bob-god-module-2"] = { tech = "bob-god-module-2", type = "module" },
    ["bob-god-module-3"] = { tech = "bob-god-module-3", type = "module" },
    ["bob-god-module-4"] = { tech = "bob-god-module-4", type = "module" },
    ["bob-god-module-5"] = { tech = "bob-god-module-5", type = "module" },
    --raw-speed-module
    ["bob-raw-speed-module-1"] = { tech = "bob-raw-speed-module-1", type = "module" },
    ["bob-raw-speed-module-2"] = { tech = "bob-raw-speed-module-2", type = "module" },
    ["bob-raw-speed-module-3"] = { tech = "bob-raw-speed-module-3", type = "module" },
    ["bob-raw-speed-module-4"] = { tech = "bob-raw-speed-module-4", type = "module" },
    ["bob-raw-speed-module-5"] = { tech = "bob-raw-speed-module-5", type = "module" },
    ["bob-raw-speed-module-6"] = { tech = "bob-raw-speed-module-6", type = "module" },
    ["bob-raw-speed-module-7"] = { tech = "bob-raw-speed-module-7", type = "module" },
    ["bob-raw-speed-module-8"] = { tech = "bob-raw-speed-module-8", type = "module" },
    --science-pack
    ["bob-automation-science-pack"] = { tech = "bob-deadlock-stacking-1", type = "tool" },
    ["bob-logistic-science-pack"] = { tech = "bob-logistic-science-pack", type = "tool" },
    ["bob-military-science-pack"] = { tech = "bob-military-science-pack", type = "tool" },
    ["bob-chemical-science-pack"] = { tech = "bob-chemical-science-pack", type = "tool" },
    ["bob-advanced-logistic-science-pack"] = { tech = "bob-advanced-logistic-science-pack", type = "tool" },
    ["bob-production-science-pack"] = { tech = "bob-production-science-pack", type = "tool" },
    ["bob-utility-science-pack"] = { tech = "bob-utility-science-pack", type = "tool" },
    ["bob-science-pack-gold"] = { tech = "bob-alien-research", type = "tool" },
    ["bob-alien-science-pack"] = { tech = "bob-alien-research", type = "tool" },
    ["bob-alien-science-pack-blue"] = { tech = "bob-alien-research", type = "tool" },
    ["bob-alien-science-pack-orange"] = { tech = "bob-alien-research", type = "tool" },
    ["bob-alien-science-pack-purple"] = { tech = "bob-alien-research", type = "tool" },
    ["bob-alien-science-pack-yellow"] = { tech = "bob-alien-research", type = "tool" },
    ["bob-alien-science-pack-green"] = { tech = "bob-alien-research", type = "tool" },
    ["bob-alien-science-pack-red"] = { tech = "bob-alien-research", type = "tool" },
    ["bob-space-science-pack"] = { tech = "bob-space-science-pack", type = "tool" },
    --speed-module
    ["bob-speed-module"] = { tech = "bob-speed-module", type = "module" },
    ["bob-speed-module-2"] = { tech = "bob-speed-module-2", type = "module" },
    ["bob-speed-module-3"] = { tech = "bob-speed-module-3", type = "module" },
    ["bob-speed-module-4"] = { tech = "bob-speed-module-4", type = "module" },
    ["bob-speed-module-5"] = { tech = "bob-speed-module-5", type = "module" },
    ["bob-speed-module-6"] = { tech = "bob-speed-module-6", type = "module" },
    ["bob-speed-module-7"] = { tech = "bob-speed-module-7", type = "module" },
    ["bob-speed-module-8"] = { tech = "bob-speed-module-8", type = "module" },
    --pipes
    ["bob-copper-pipe"] = {},
    ["bob-pipe"] = {},
    ["bob-stone-pipe"] = {},
    ["bob-bronze-pipe"] = {},
    ["bob-steel-pipe"] = {},
    ["bob-plastic-pipe"] = {},
    ["bob-brass-pipe"] = {},
    ["bob-titanium-pipe"] = {},
    ["bob-ceramic-pipe"] = {},
    ["bob-tungsten-pipe"] = {},
    ["bob-nitinol-pipe"] = {},
    ["bob-copper-tungsten-pipe"] = {},
    ["bob-copper-pipe-to-ground"] = {},
    ["bob-pipe-to-ground"] = {},
    ["bob-stone-pipe-to-ground"] = {},
    ["bob-bronze-pipe-to-ground"] = {},
    ["bob-steel-pipe-to-ground"] = {},
    ["bob-plastic-pipe-to-ground"] = {},
    ["bob-brass-pipe-to-ground"] = {},
    ["bob-titanium-pipe-to-ground"] = {},
    ["bob-ceramic-pipe-to-ground"] = {},
    ["bob-tungsten-pipe-to-ground"] = {},
    ["bob-nitinol-pipe-to-ground"] = {},
    ["bob-copper-tungsten-pipe-to-ground"] = {},
    --heat pipes
    ["bob-heat-pipe"] = {},
    ["bob-heat-pipe-2"] = {},
    ["bob-heat-pipe-3"] = {},
    ["bob-heat-shield-tile"] = {},
    --chests
    ["bob-brass-chest"] = {},
    ["bob-steel-chest"] = {},
    ["bob-titanium-chest"] = {},
    --science ingredients
    ["bob-stone-wall"] = {},
    ["bob-firearm-magazine"] = { type = "ammo" },
    ["bob-piercing-rounds-magazine"] = { type = "ammo" },
    ["bob-grenade"] = { type = "capsule" },
    ["bob-flying-robot-frame"] = {},
    ["bob-electric-furnace"] = {},
    ["bob-chemical-plant"] = {},
    ["bob-assembling-machine-1"] = {},
    ["bob-assembling-machine-2"] = {},
    --rail
    ["rail"] = { tier = "railway", type = "rail-planner" },
    --tile
    ["landfill"] = {},
    ["concrete"] = {},
    ["hazard-concrete"] = {},
    ["refined-concrete"] = {},
    ["refined-hazard-concrete"] = {}
}

return Items
